import Head from 'next/head'
import { motion } from 'framer-motion';
import { useState } from 'react';

const variants = {
  onScreen: { opacity: 1, x: 0 },
  offScreen: { opacity: 0, x: "-100%" }
}

export default function Home() {
  const [isOnScreen, setIsOnScreen] = useState(false);
  return (
    <div>
      <Head>
        <title>Howl At the Moon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center min-h-screen bg-gradient-to-b from-background_mood-dark to-transparent">
        <section className="relative w-full h-screen flex items-center justify-center overflow-hidden">
          <motion.div animate={isOnScreen ? "onScreen" : "offScreen"} variants={variants}>
            <img className="background-image h-full object-cover" src="./stars.png" alt="Stars on Background" />
          </motion.div>

          <img className="background-image mix-blend-screen" src="./moon.png" alt="Moon on Background" />
          <img className="background-image clip-background" src="./mountains_behind.png" alt="Mountains on Background" />
          <h2 className="absolute text-white text-uni  font-bold">Slow Down</h2>

          <a href="#" onClick={() => setIsOnScreen(isOnScreen => !isOnScreen)} id="#cta" className="absolute whitespace-nowrap	 top-1/2 left-1/2 translate-50 inline-block rounded-full text-2xl px-20 bg-white py-4 z-50 mt-32" >Howl With Us</a>
          <img className="background-image z-50 clip-background text-background_mood-dark" src="./mountains_front.png" alt="Mountains on Background" />
        </section>
      </main>
    </div>
  )
}
